package org.metadatacenter.submission.biosample.core;

import biosample.TypeAttribute;
import biosample.TypeBioSample;
import biosample.TypeBioSampleIdentifier;
import common.sp.TypeDescriptor;
import common.sp.TypeOrganism;
import common.sp.TypePrimaryId;
import common.sp.TypeRefId;
import generated.BioSampleValidate;
import generated.TypeActionStatus;
import generated.TypeContactInfo;
import generated.TypeName;
import generated.TypeOrganization;
import generated.TypeStatus;
import generated.TypeSubmission;
import org.apache.http.HttpEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.metadatacenter.submission.biosample.AMIA2016DemoBioSampleTemplate;
import org.metadatacenter.submission.biosample.CEDARBioSampleValidationResponse;
import org.metadatacenter.submission.biosample.OptionalAttribute;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

public class BioSampleValidator
{
  private static final String BIOSAMPLE_VALIDATION_URL = "https://www.ncbi.nlm.nih.gov/projects/biosample/validate/";

  /**
   * Take an instance of the CEDAR BioSample template developed for the 2016 AMIA demo, convert
   * it to a BioSample XML-based submission, submit it to the BioSample validator, and return
   * the results of the validation.
   * <p>
   * The {@link AMIA2016DemoBioSampleTemplate} class is generated by jsonschems2pojo from the
   * AMIA2016DemoBioSampleTemplate.json JSON Schema file in the resources directory. This file
   * contains the CEDAR template that defines the example BioSample submission used for the 2016 AMIA demo.
   * <p>
   * The {@link CEDARBioSampleValidationResponse} class is generated by jsonschems2pojo from the
   * CEDARBioSampleValidationResponse.json JSON Schema file in the resources directory. It
   * is the CEDAR representation of the response from the BioSample validator.
   *
   * @param amia2016DemoBioSampleSubmissionInstance An instance of the AMIA demo BioSample submission template
   * @return The BioSample validation response
   * @throws IOException                    If an IO error occurs during processing
   * @throws JAXBException                  If a JAXB error occurs during processing
   * @throws DatatypeConfigurationException If a configuration error occurs during processing
   */
  public CEDARBioSampleValidationResponse validateAMIA2016DemoBioSampleSubmission(
    AMIA2016DemoBioSampleTemplate amia2016DemoBioSampleSubmissionInstance)
    throws IOException, JAXBException, DatatypeConfigurationException
  {
    CloseableHttpClient client = HttpClientBuilder.create().build();
    HttpPost post = new HttpPost(BIOSAMPLE_VALIDATION_URL);
    String submissionXML = generateBioSampleSubmissionXML(amia2016DemoBioSampleSubmissionInstance);
    StringEntity requestEntity = new StringEntity(submissionXML, ContentType.APPLICATION_XML);

    post.setHeader("Accept", "application/xml");
    post.setHeader("Content-type", "application/xml");
    post.setEntity(requestEntity);

    CloseableHttpResponse response = client.execute(post);

    try {
      if (response.getStatusLine().getStatusCode() == 200) {
        HttpEntity entity = response.getEntity();
        InputStream xmlResponseStream = entity.getContent();
        BioSampleValidate bioSampleValidationResponse = bioSampleXMLResponse2BioSampleValidate(xmlResponseStream);
        return bioSampleValidationResponse2CEDARValidationResponse(bioSampleValidationResponse);
      } else
        return generateUnexpectedStatusCodeCEDARBioSampleValidationResponse(response.getStatusLine().getStatusCode());
    } finally {
      response.close();
    }
  }

  /**
   * The {@link CEDARBioSampleValidationResponse} class is generated by jsonschems2pojo from the
   * CEDARBioSampleValidationResponse.json JSON Schema file in the resources directory.
   *
   * @param statusCode A HTTP status code
   * @return A validation response message
   */
  private CEDARBioSampleValidationResponse generateUnexpectedStatusCodeCEDARBioSampleValidationResponse(int statusCode)
  {
    CEDARBioSampleValidationResponse cedarValidationResponse = new CEDARBioSampleValidationResponse();
    List<String> messages = new ArrayList<>();
    String message = "Unexpected status code " + statusCode + " returned by BioSample validation service";
    cedarValidationResponse.setMessages(messages);
    messages.add(message);
    cedarValidationResponse.setIsValid(false);

    return cedarValidationResponse;
  }

  /**
   * The {@link CEDARBioSampleValidationResponse} class is generated by jsonschems2pojo from the
   * CEDARBioSampleValidationResponse.json JSON Schema file in the resources directory.
   * <p>
   * The {@link BioSampleValidate} class is generated by JAXB from the submission-response.xsd file
   * in the resources directory. It represents a response from the BioSample validator.
   *
   * @param bioSampleValidationResponse A BioSample validation response
   * @return A CEDAR
   */
  private CEDARBioSampleValidationResponse bioSampleValidationResponse2CEDARValidationResponse(
    BioSampleValidate bioSampleValidationResponse)
  {
    CEDARBioSampleValidationResponse cedarValidationResponse = new CEDARBioSampleValidationResponse();
    List<String> messages = new ArrayList<>();
    cedarValidationResponse.setMessages(messages);

    List<TypeActionStatus> actionStatuses = bioSampleValidationResponse.getAction();
    if (!actionStatuses.isEmpty()) {
      TypeActionStatus actionStatus = actionStatuses.get(0);
      TypeStatus status = actionStatus.getStatus();
      if (status == TypeStatus.PROCESSED_OK)
        cedarValidationResponse.setIsValid(true);
      else
        cedarValidationResponse.setIsValid(false);

      // There can be warning messages from the validator even if validation passes
      List<TypeActionStatus.Response> statusResponses = actionStatus.getResponse();
      for (TypeActionStatus.Response statusResponse : statusResponses) {
        String message = statusResponse.getMessage().getValue();
        messages.add(message);
      }
    }
    return cedarValidationResponse;
  }

  /**
   * The {@link AMIA2016DemoBioSampleTemplate} class is generated by jsonschems2pojo from the
   * AMIA2016DemoBioSampleTemplate.json JSON Schema file in the resources directory.
   *
   * @param amia2016DemoBioSampleSubmission An AMIA demo BioSample submission
   * @return A string containing an BioSample-conformant XML representation of the supplied submission
   * @throws DatatypeConfigurationException If a configuration error occurs during processing
   * @throws JAXBException                  If a configuration error occurs during processing
   */
  private String generateBioSampleSubmissionXML(AMIA2016DemoBioSampleTemplate amia2016DemoBioSampleSubmission)
    throws DatatypeConfigurationException, JAXBException
  {
    generated.ObjectFactory objectFactory = new generated.ObjectFactory();
    biosample.ObjectFactory biosampleObjectFactory = new biosample.ObjectFactory();
    common.sp.ObjectFactory spCommonObjectFactory = new common.sp.ObjectFactory();

    TypeSubmission xmlSubmission = objectFactory.createTypeSubmission();

    // Submission/Description/Comment
    TypeSubmission.Description description = objectFactory.createTypeSubmissionDescription();
    xmlSubmission.setDescription(description);
    description.setComment("Example CEDAR-generated BioSample submission using the Human.1.0 package");

    // Submission/Description/Hold/releaseDate
    TypeSubmission.Description.Hold hold = objectFactory.createTypeSubmissionDescriptionHold();
    description.setHold(hold);
    hold.setReleaseDate(createXMLGregorianCalendar("2016-10-10"));

    // Submission/Description/Organization
    TypeOrganization organization = objectFactory.createTypeOrganization();
    description.getOrganization().add(organization);
    organization.setRole("master");
    organization.setType("institute");

    // Submission/Description/Organization/Name
    TypeOrganization.Name organizationName = objectFactory.createTypeOrganizationName();
    organization.setName(organizationName);
    organizationName.setValue("CEDAR");

    // Submission/Description/Organization/ContactInfo/email
    TypeContactInfo contactInfo = objectFactory.createTypeContactInfo();
    organization.getContact().add(contactInfo);
    contactInfo.setEmail("metadatacenter@gmail.com");

    // Submission/Description/Organization/ContactInfo/Name
    TypeName name = objectFactory.createTypeName();
    contactInfo.setName(name);
    name.setFirst("Mr.");
    name.setLast("CEDAR");

    // Submission/Action
    TypeSubmission.Action action = objectFactory.createTypeSubmissionAction();
    xmlSubmission.getAction().add(action);

    // Submission/Action/AddData/target_db
    TypeSubmission.Action.AddData addData = objectFactory.createTypeSubmissionActionAddData();
    action.setAddData(addData);
    addData.setTargetDb("BioSample");

    // Submission/Action/AddData/Data/content_type
    TypeSubmission.Action.AddData.Data data = objectFactory.createTypeSubmissionActionAddDataData();
    addData.getData().add(data);
    data.setContentType("XML");

    // Submission/Action/AddData/Data/XMLContent
    TypeSubmission.Action.AddData.Data.XmlContent xmlContent = objectFactory.createTypeInlineDataXmlContent();
    data.setXmlContent(xmlContent);

    // Submission/Action/AddData/Data/XMLContent/BioSample/schema_version
    TypeBioSample bioSample = biosampleObjectFactory.createTypeBioSample();
    xmlContent.setBioSample(bioSample);
    bioSample.setSchemaVersion("2.0");

    // Submission/Action/AddData/Data/XMLContent/BioSample/SampleID
    TypeBioSampleIdentifier sampleID = biosampleObjectFactory.createTypeBioSampleIdentifier();
    bioSample.setSampleId(sampleID);

    // Submission/Action/AddData/Data/XMLContent/BioSample/SampleID/SPUID
    TypeBioSampleIdentifier.SPUID spuid = biosampleObjectFactory.createTypeBioSampleIdentifierSPUID();
    sampleID.getSPUID().add(spuid);
    spuid.setSpuidNamespace("CEDAR");
    spuid.setValue(amia2016DemoBioSampleSubmission.getSampleName().getValue());

    // Submission/Action/AddData/Data/XMLContent/BioSample/Descriptor
    TypeDescriptor descriptor = spCommonObjectFactory.createTypeDescriptor();
    bioSample.setDescriptor(descriptor);
    descriptor.setTitle("Example CEDAR-generated BioSample submission using the Human.1.0 package");

    // Submission/Action/AddData/Data/XMLContent/BioSample/Organism
    TypeOrganism organism = spCommonObjectFactory.createTypeOrganism();
    bioSample.setOrganism(organism);
    if (amia2016DemoBioSampleSubmission.getOrganism().getValueLabel() != null)
      organism.setOrganismName(amia2016DemoBioSampleSubmission.getOrganism().getValueLabel());
    else
      organism.setOrganismName("");

    // Submission/Action/AddData/Data/XMLContent/BioSample/BioProject
    TypeRefId bioProject = spCommonObjectFactory.createTypeRefId();
    bioSample.getBioProject().add(bioProject);

    // Submission/Action/AddData/Data/XMLContent/BioSample/BioProject/PrimaryID
    TypePrimaryId bioProjectPrimaryID = spCommonObjectFactory.createTypePrimaryId();
    bioProject.setPrimaryId(bioProjectPrimaryID);
    bioProjectPrimaryID.setDb("BioProject");
    bioProjectPrimaryID.setValue("PRJNA212117");

    // Submission/Action/AddData/Data/XMLContent/BioSample/Package
    bioSample.setPackage("Human.1.0");

    // Submission/Action/AddData/Data/XMLContent/BioSample/Attributes
    TypeBioSample.Attributes attributes = biosampleObjectFactory.createTypeBioSampleAttributes();
    bioSample.setAttributes(attributes);

    // Submission/Action/AddData/Data/XMLContent/BioSample/Attributes/Attribute

    // Required attributes
    TypeAttribute attribute = biosampleObjectFactory.createTypeAttribute();
    attributes.getAttribute().add(attribute);
    attribute.setAttributeName("isolate");
    attribute.setValue(amia2016DemoBioSampleSubmission.getIsolate().getValue());

    attribute = biosampleObjectFactory.createTypeAttribute();
    attributes.getAttribute().add(attribute);
    attribute.setAttributeName("age");
    attribute.setValue(amia2016DemoBioSampleSubmission.getAge().getValue());

    attribute = biosampleObjectFactory.createTypeAttribute();
    attributes.getAttribute().add(attribute);
    attribute.setAttributeName("sex");
    attribute.setValue(amia2016DemoBioSampleSubmission.getSex().getValueLabel());

    attribute = biosampleObjectFactory.createTypeAttribute();
    attributes.getAttribute().add(attribute);
    attribute.setAttributeName("biomaterial provider");
    attribute.setValue(amia2016DemoBioSampleSubmission.getBiomaterialProvider().getValue());

    attribute = biosampleObjectFactory.createTypeAttribute();
    attributes.getAttribute().add(attribute);
    attribute.setAttributeName("tissue");
    attribute.setValue(amia2016DemoBioSampleSubmission.getTissue().getValueLabel());

    for (OptionalAttribute optionalAttribute : amia2016DemoBioSampleSubmission.getOptionalAttribute()) {
      attribute = biosampleObjectFactory.createTypeAttribute();
      attributes.getAttribute().add(attribute);
      attribute.setAttributeName(optionalAttribute.getName().getValue());
      attribute.setValue(optionalAttribute.getValue().getValue());
    }
    StringWriter writer = new StringWriter();

    JAXBElement<TypeSubmission> submissionRoot = objectFactory.createSubmission(xmlSubmission);
    JAXBContext ctx = JAXBContext.newInstance(TypeSubmission.class);
    Marshaller marshaller = ctx.createMarshaller();
    marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
    //marshaller.marshal(submissionRoot, System.out);
    marshaller.marshal(submissionRoot, writer);

    return writer.toString();
  }

  /**
   * The {@link BioSampleValidate} class is generated by JAXB from the submission-response.xsd file
   * in the resources directory. It represents a response from the BioSample validator.
   *
   * @param xmlResponseStream A stream containing the XML response from the BioSample validator
   * @return A Java representation of the XML response
   * @throws JAXBException If there is an error during processing
   */
  private BioSampleValidate bioSampleXMLResponse2BioSampleValidate(InputStream xmlResponseStream) throws JAXBException
  {
    JAXBContext jaxbBioSampleValidateContext = JAXBContext.newInstance(BioSampleValidate.class);
    Unmarshaller jaxbBioSampleValidateUnmarshaller = jaxbBioSampleValidateContext.createUnmarshaller();
    BioSampleValidate bioSampleValidate = (BioSampleValidate)jaxbBioSampleValidateUnmarshaller
      .unmarshal(xmlResponseStream);
    return bioSampleValidate;
  }

  private XMLGregorianCalendar createXMLGregorianCalendar(String date) throws DatatypeConfigurationException
  {
    DatatypeFactory datatypeFactory = DatatypeFactory.newInstance();
    GregorianCalendar gc = new GregorianCalendar();

    return datatypeFactory.newXMLGregorianCalendar(gc);
  }
}
